# coding: utf-8

"""
Fireblocks API

Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)

The version of the OpenAPI document: 1.6.2
Contact: developers@fireblocks.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from fireblocks.api.connected_accounts_beta_api import ConnectedAccountsBetaApi


class TestConnectedAccountsBetaApi(unittest.TestCase):
    """ConnectedAccountsBetaApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConnectedAccountsBetaApi()

    def tearDown(self) -> None:
        pass

    def test_disconnect_connected_account(self) -> None:
        """Test case for disconnect_connected_account

        Disconnect connected account
        """
        pass

    def test_get_connected_account(self) -> None:
        """Test case for get_connected_account

        Get connected account
        """
        pass

    def test_get_connected_account_balances(self) -> None:
        """Test case for get_connected_account_balances

        Get balances for an account
        """
        pass

    def test_get_connected_account_rates(self) -> None:
        """Test case for get_connected_account_rates

        Get exchange rates for an account
        """
        pass

    def test_get_connected_account_trading_pairs(self) -> None:
        """Test case for get_connected_account_trading_pairs

        Get supported trading pairs for an account
        """
        pass

    def test_get_connected_accounts(self) -> None:
        """Test case for get_connected_accounts

        Get connected accounts
        """
        pass

    def test_rename_connected_account(self) -> None:
        """Test case for rename_connected_account

        Rename Connected Account
        """
        pass


if __name__ == "__main__":
    unittest.main()
