# coding: utf-8

"""
Fireblocks API

Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)

The version of the OpenAPI document: 1.6.2
Contact: developers@fireblocks.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from fireblocks.models.tr_link_vasp_list_dto import TRLinkVaspListDto


class TestTRLinkVaspListDto(unittest.TestCase):
    """TRLinkVaspListDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TRLinkVaspListDto:
        """Test TRLinkVaspListDto
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TRLinkVaspListDto`
        """
        model = TRLinkVaspListDto()
        if include_optional:
            return TRLinkVaspListDto(
                id = 'did:ethr:0x1234567890abcdef',
                name = 'ACME Virtual Assets',
                legal_name = 'ACME Virtual Assets Corporation',
                national_identification = fireblocks.models.tr_link_vasp_national_identification.TRLinkVaspNationalIdentification(
                    identifier = '123456789', 
                    type = 'LEI', 
                    authority = 'Financial Conduct Authority', ),
                geographic_address = fireblocks.models.tr_link_vasp_geographic_address.TRLinkVaspGeographicAddress(
                    formatted_address = '123 Main Street, New York, NY 10001, USA', 
                    country = 'USA', 
                    street_name = 'Main Street', 
                    building_number = '123', 
                    city = 'New York', 
                    postal_code = '10001', )
            )
        else:
            return TRLinkVaspListDto(
                id = 'did:ethr:0x1234567890abcdef',
                name = 'ACME Virtual Assets',
        )
        """

    def testTRLinkVaspListDto(self):
        """Test TRLinkVaspListDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
