# coding: utf-8

"""
    Fireblocks API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.6.2
    Contact: support@fireblocks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import fireblocks_client
from fireblocks_client.models.create_connection_request import CreateConnectionRequest  # noqa: E501
from fireblocks_client.rest import ApiException

class TestCreateConnectionRequest(unittest.TestCase):
    """CreateConnectionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CreateConnectionRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateConnectionRequest`
        """
        model = fireblocks_client.models.create_connection_request.CreateConnectionRequest()  # noqa: E501
        if include_optional :
            return CreateConnectionRequest(
                vault_account_id = 1, 
                fee_level = 'MEDIUM', 
                uri = 'wc:77752975-906f-48f5-b59f-047826ee947e@1?bridge=https%3A%2F%2F0.bridge.walletconnect.org&key=64be99adc6086b7a729b0ec8c7e1f174927ab92e84f5c6f9527050225344a637', 
                chain_ids = ["ETH","ETH_TEST"]
            )
        else :
            return CreateConnectionRequest(
                vault_account_id = 1,
                fee_level = 'MEDIUM',
                uri = 'wc:77752975-906f-48f5-b59f-047826ee947e@1?bridge=https%3A%2F%2F0.bridge.walletconnect.org&key=64be99adc6086b7a729b0ec8c7e1f174927ab92e84f5c6f9527050225344a637',
                chain_ids = ["ETH","ETH_TEST"],
        )
        """

    def testCreateConnectionRequest(self):
        """Test CreateConnectionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
