# coding: utf-8

"""
Fireblocks API

Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)

The version of the OpenAPI document: 1.6.2
Contact: developers@fireblocks.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from fireblocks.models.register_approval_api_key_request import (
    RegisterApprovalApiKeyRequest,
)


class TestRegisterApprovalApiKeyRequest(unittest.TestCase):
    """RegisterApprovalApiKeyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RegisterApprovalApiKeyRequest:
        """Test RegisterApprovalApiKeyRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `RegisterApprovalApiKeyRequest`
        """
        model = RegisterApprovalApiKeyRequest()
        if include_optional:
            return RegisterApprovalApiKeyRequest(
                name = 'primary signing key',
                approval_api_public_key = fireblocks.models.approval_api_public_key.ApprovalApiPublicKey(
                    algorithm = 'ECDSA_SECP256R1', 
                    public_key_pem = '-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQ...
-----END PUBLIC KEY-----', )
            )
        else:
            return RegisterApprovalApiKeyRequest(
                name = 'primary signing key',
                approval_api_public_key = fireblocks.models.approval_api_public_key.ApprovalApiPublicKey(
                    algorithm = 'ECDSA_SECP256R1', 
                    public_key_pem = '-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQ...
-----END PUBLIC KEY-----', ),
        )
        """

    def testRegisterApprovalApiKeyRequest(self):
        """Test RegisterApprovalApiKeyRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
