# coding: utf-8

"""
Fireblocks API

Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)

The version of the OpenAPI document: 1.6.2
Contact: developers@fireblocks.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from fireblocks.models.delegation_summary import DelegationSummary


class TestDelegationSummary(unittest.TestCase):
    """DelegationSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DelegationSummary:
        """Test DelegationSummary
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `DelegationSummary`
        """
        model = DelegationSummary()
        if include_optional:
            return DelegationSummary(
                active = [
                    fireblocks.models.amount_and_chain_descriptor.AmountAndChainDescriptor(
                        chain_descriptor = 'ETH', 
                        amount = '32.007149606', )
                    ],
                inactive = [
                    fireblocks.models.amount_and_chain_descriptor.AmountAndChainDescriptor(
                        chain_descriptor = 'ETH', 
                        amount = '32.007149606', )
                    ],
                rewards_amount = [
                    fireblocks.models.amount_and_chain_descriptor.AmountAndChainDescriptor(
                        chain_descriptor = 'ETH', 
                        amount = '32.007149606', )
                    ],
                total_staked = [
                    fireblocks.models.amount_and_chain_descriptor.AmountAndChainDescriptor(
                        chain_descriptor = 'ETH', 
                        amount = '32.007149606', )
                    ]
            )
        else:
            return DelegationSummary(
                active = [
                    fireblocks.models.amount_and_chain_descriptor.AmountAndChainDescriptor(
                        chain_descriptor = 'ETH', 
                        amount = '32.007149606', )
                    ],
                inactive = [
                    fireblocks.models.amount_and_chain_descriptor.AmountAndChainDescriptor(
                        chain_descriptor = 'ETH', 
                        amount = '32.007149606', )
                    ],
                rewards_amount = [
                    fireblocks.models.amount_and_chain_descriptor.AmountAndChainDescriptor(
                        chain_descriptor = 'ETH', 
                        amount = '32.007149606', )
                    ],
                total_staked = [
                    fireblocks.models.amount_and_chain_descriptor.AmountAndChainDescriptor(
                        chain_descriptor = 'ETH', 
                        amount = '32.007149606', )
                    ],
        )
        """

    def testDelegationSummary(self):
        """Test DelegationSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
