# coding: utf-8

"""
Fireblocks API

Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)

The version of the OpenAPI document: 1.6.2
Contact: developers@fireblocks.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from fireblocks.api.keys_beta_api import KeysBetaApi


class TestKeysBetaApi(unittest.TestCase):
    """KeysBetaApi unit test stubs"""

    def setUp(self) -> None:
        self.api = KeysBetaApi()

    def tearDown(self) -> None:
        pass

    def test_get_mpc_keys_list(self) -> None:
        """Test case for get_mpc_keys_list

        Get list of mpc keys
        """
        pass

    def test_get_mpc_keys_list_by_user(self) -> None:
        """Test case for get_mpc_keys_list_by_user

        Get list of mpc keys by `userId`
        """
        pass


if __name__ == "__main__":
    unittest.main()
