# coding: utf-8

"""
Fireblocks API

Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)

The version of the OpenAPI document: 1.6.2
Contact: developers@fireblocks.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from fireblocks.models.update_asset_user_metadata_request import (
    UpdateAssetUserMetadataRequest,
)


class TestUpdateAssetUserMetadataRequest(unittest.TestCase):
    """UpdateAssetUserMetadataRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateAssetUserMetadataRequest:
        """Test UpdateAssetUserMetadataRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `UpdateAssetUserMetadataRequest`
        """
        model = UpdateAssetUserMetadataRequest()
        if include_optional:
            return UpdateAssetUserMetadataRequest(
                metadata = fireblocks.models.asset_metadata_request.AssetMetadataRequest(
                    note = fireblocks.models.asset_note_request.AssetNoteRequest(
                        text = 'Pay attention to ETH gas fees', ), )
            )
        else:
            return UpdateAssetUserMetadataRequest(
        )
        """

    def testUpdateAssetUserMetadataRequest(self):
        """Test UpdateAssetUserMetadataRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
