# coding: utf-8

"""
    Fireblocks API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.6.2
    Contact: support@fireblocks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import fireblocks_client
from fireblocks_client.api.external_wallets_api import ExternalWalletsApi  # noqa: E501
from fireblocks_client.rest import ApiException
import importlib
import os
import sys

class TestExternalWalletsApi(unittest.TestCase):
    """ExternalWalletsApi unit test stubs"""
    os.environ["FIREBLOCKS_API_KEY"] = ""
    os.environ["FIREBLOCKS_SECRET_KEY"]  = ""
    def setUp(self):
        self.api = fireblocks_client.api.external_wallets_api.ExternalWalletsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_asset_to_external_wallet(self):
        """Test case for add_asset_to_external_wallet

        Add an asset to an external wallet.  # noqa: E501
        """
        pass

    def test_create_external_wallet(self):
        """Test case for create_external_wallet

        Create an external wallet  # noqa: E501
        """
        pass

    def test_delete_external_wallet(self):
        """Test case for delete_external_wallet

        Delete an external wallet  # noqa: E501
        """
        pass

    def test_get_asset_in_external_wallet(self):
        """Test case for get_asset_in_external_wallet

        Get an asset from an external wallet  # noqa: E501
        """
        pass

    def test_get_external_wallet_by_id(self):
        """Test case for get_external_wallet_by_id

        Find an external wallet  # noqa: E501
        """
        pass

    def test_get_external_wallets(self):
        """Test case for get_external_wallets

        List external wallets  # noqa: E501
        """
        pass

    def test_remove_asset_from_external_wallet(self):
        """Test case for remove_asset_from_external_wallet

        Delete an asset from an external wallet  # noqa: E501
        """
        pass

    def test_set_customer_ref_id_for_external_wallet(self):
        """Test case for set_customer_ref_id_for_external_wallet

        Set an AML customer reference ID for an external wallet  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()