# coding: utf-8

"""
Fireblocks API

Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)

The version of the OpenAPI document: 1.6.2
Contact: developers@fireblocks.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from fireblocks.models.pix_destination import PixDestination


class TestPixDestination(unittest.TestCase):
    """PixDestination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PixDestination:
        """Test PixDestination
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PixDestination`
        """
        model = PixDestination()
        if include_optional:
            return PixDestination(
                type = 'PIX',
                address = {"accountHolder":{"name":"Maria Silva Santos","city":"São Paulo","country":"BR","subdivision":"SP","address":"Rua das Flores, 123","postalCode":"01234-567"},"pixKey":"11987654321","keyType":"phone","bankName":"Banco do Brasil","bankCode":"001","qrCode":"qr_code_number","expirationDate":"2025-01-15T12:00:00Z"}
            )
        else:
            return PixDestination(
                type = 'PIX',
                address = {"accountHolder":{"name":"Maria Silva Santos","city":"São Paulo","country":"BR","subdivision":"SP","address":"Rua das Flores, 123","postalCode":"01234-567"},"pixKey":"11987654321","keyType":"phone","bankName":"Banco do Brasil","bankCode":"001","qrCode":"qr_code_number","expirationDate":"2025-01-15T12:00:00Z"},
        )
        """

    def testPixDestination(self):
        """Test PixDestination"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
