# coding: utf-8

"""
Fireblocks API

Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)

The version of the OpenAPI document: 1.6.2
Contact: developers@fireblocks.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from fireblocks.models.identification import Identification


class TestIdentification(unittest.TestCase):
    """Identification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Identification:
        """Test Identification
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Identification`
        """
        model = Identification()
        if include_optional:
            return Identification(
                external_reference_id = '',
                entity_type = 'BUSINESS',
                participant_relationship_type = 'FirstParty',
                full_name = fireblocks.models.personal_identification_full_name.PersonalIdentification_fullName(
                    first_name = '', 
                    last_name = '', ),
                date_of_birth = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                postal_address = {"streetName":"Fifth Avenue","buildingNumber":"350","postalCode":"10118","city":"New York","subdivision":"NY","district":"Manhattan","country":"US"},
                email = '',
                phone = '+14155551234',
                business_name = '',
                registration_number = ''
            )
        else:
            return Identification(
                external_reference_id = '',
                entity_type = 'BUSINESS',
                participant_relationship_type = 'FirstParty',
                full_name = fireblocks.models.personal_identification_full_name.PersonalIdentification_fullName(
                    first_name = '', 
                    last_name = '', ),
                date_of_birth = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                postal_address = {"streetName":"Fifth Avenue","buildingNumber":"350","postalCode":"10118","city":"New York","subdivision":"NY","district":"Manhattan","country":"US"},
                business_name = '',
                registration_number = '',
        )
        """

    def testIdentification(self):
        """Test Identification"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
