# coding: utf-8

"""
Fireblocks API

Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)

The version of the OpenAPI document: 1.6.2
Contact: developers@fireblocks.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from fireblocks.models.tr_link_get_supported_asset_response import (
    TRLinkGetSupportedAssetResponse,
)


class TestTRLinkGetSupportedAssetResponse(unittest.TestCase):
    """TRLinkGetSupportedAssetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TRLinkGetSupportedAssetResponse:
        """Test TRLinkGetSupportedAssetResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TRLinkGetSupportedAssetResponse`
        """
        model = TRLinkGetSupportedAssetResponse()
        if include_optional:
            return TRLinkGetSupportedAssetResponse(
                fireblocks_asset = fireblocks.models.tr_link_public_asset_info.TRLinkPublicAssetInfo(
                    id = 'USDC_ETH', 
                    name = 'USD Coin', 
                    type = 'ERC20', 
                    contract_address = '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', 
                    native_asset = 'ETH', 
                    decimals = 6, 
                    issuer_address = '0x1234567890abcdef1234567890abcdef12345678', ),
                partner_response = {"assetCode":"USDC","network":"ethereum","enabled":true},
                partner_can_handle_any_asset = False,
                note = 'Partner supports only explicitly listed assets',
                supported = True
            )
        else:
            return TRLinkGetSupportedAssetResponse(
                fireblocks_asset = fireblocks.models.tr_link_public_asset_info.TRLinkPublicAssetInfo(
                    id = 'USDC_ETH', 
                    name = 'USD Coin', 
                    type = 'ERC20', 
                    contract_address = '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', 
                    native_asset = 'ETH', 
                    decimals = 6, 
                    issuer_address = '0x1234567890abcdef1234567890abcdef12345678', ),
                partner_response = {"assetCode":"USDC","network":"ethereum","enabled":true},
                partner_can_handle_any_asset = False,
                note = 'Partner supports only explicitly listed assets',
                supported = True,
        )
        """

    def testTRLinkGetSupportedAssetResponse(self):
        """Test TRLinkGetSupportedAssetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
