# coding: utf-8

"""
Fireblocks API

Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)

The version of the OpenAPI document: 1.6.2
Contact: developers@fireblocks.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from fireblocks.models.account_based_access_provider_info import (
    AccountBasedAccessProviderInfo,
)


class TestAccountBasedAccessProviderInfo(unittest.TestCase):
    """AccountBasedAccessProviderInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountBasedAccessProviderInfo:
        """Test AccountBasedAccessProviderInfo
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `AccountBasedAccessProviderInfo`
        """
        model = AccountBasedAccessProviderInfo()
        if include_optional:
            return AccountBasedAccessProviderInfo(
                connected = True,
                accounts = [
                    {"id":"acc_9f4e2d8b1c6a5e73","name":"Main Trading Account"}
                    ]
            )
        else:
            return AccountBasedAccessProviderInfo(
                connected = True,
                accounts = [
                    {"id":"acc_9f4e2d8b1c6a5e73","name":"Main Trading Account"}
                    ],
        )
        """

    def testAccountBasedAccessProviderInfo(self):
        """Test AccountBasedAccessProviderInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
