# coding: utf-8

"""
Fireblocks API

Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)

The version of the OpenAPI document: 1.6.2
Contact: developers@fireblocks.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from fireblocks.models.set_ota_status_response_one_of import SetOtaStatusResponseOneOf


class TestSetOtaStatusResponseOneOf(unittest.TestCase):
    """SetOtaStatusResponseOneOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetOtaStatusResponseOneOf:
        """Test SetOtaStatusResponseOneOf
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SetOtaStatusResponseOneOf`
        """
        model = SetOtaStatusResponseOneOf()
        if include_optional:
            return SetOtaStatusResponseOneOf(
                message = 'No change needed. The current status is false'
            )
        else:
            return SetOtaStatusResponseOneOf(
        )
        """

    def testSetOtaStatusResponseOneOf(self):
        """Test SetOtaStatusResponseOneOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
