# coding: utf-8

"""
Fireblocks API

Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)

The version of the OpenAPI document: 1.6.2
Contact: developers@fireblocks.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from fireblocks.api.cosigners_beta_api import CosignersBetaApi


class TestCosignersBetaApi(unittest.TestCase):
    """CosignersBetaApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CosignersBetaApi()

    def tearDown(self) -> None:
        pass

    def test_add_cosigner(self) -> None:
        """Test case for add_cosigner

        Add cosigner
        """
        pass

    def test_get_api_key(self) -> None:
        """Test case for get_api_key

        Get API key
        """
        pass

    def test_get_api_keys(self) -> None:
        """Test case for get_api_keys

        Get all API keys
        """
        pass

    def test_get_cosigner(self) -> None:
        """Test case for get_cosigner

        Get cosigner
        """
        pass

    def test_get_cosigners(self) -> None:
        """Test case for get_cosigners

        Get all cosigners
        """
        pass

    def test_get_request_status(self) -> None:
        """Test case for get_request_status

        Get request status
        """
        pass

    def test_pair_api_key(self) -> None:
        """Test case for pair_api_key

        Pair API key
        """
        pass

    def test_rename_cosigner(self) -> None:
        """Test case for rename_cosigner

        Rename cosigner
        """
        pass

    def test_unpair_api_key(self) -> None:
        """Test case for unpair_api_key

        Unpair API key
        """
        pass

    def test_update_callback_handler(self) -> None:
        """Test case for update_callback_handler

        Update API key callback handler
        """
        pass


if __name__ == "__main__":
    unittest.main()
