# coding: utf-8

"""
    Fireblocks API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.6.2
    Contact: support@fireblocks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import fireblocks_client
from fireblocks_client.models.transaction_response_destination import TransactionResponseDestination  # noqa: E501
from fireblocks_client.rest import ApiException

class TestTransactionResponseDestination(unittest.TestCase):
    """TransactionResponseDestination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TransactionResponseDestination
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionResponseDestination`
        """
        model = fireblocks_client.models.transaction_response_destination.TransactionResponseDestination()  # noqa: E501
        if include_optional :
            return TransactionResponseDestination(
                amount = '', 
                amount_usd = '', 
                aml_screening_result = fireblocks_client.models.aml_screening_result.AmlScreeningResult(
                    provider = '', 
                    payload = fireblocks_client.models.payload.payload(), ), 
                destination = None, 
                authorization_info = fireblocks_client.models.authorization_info.AuthorizationInfo(
                    allow_operator_as_authorizer = True, 
                    logic = 'AND', 
                    groups = [
                        fireblocks_client.models.authorization_groups.AuthorizationGroups(
                            th = 1.337, 
                            users = {
                                'PENDING_AUTHORIZATION' : 'PENDING_AUTHORIZATION'
                                }, )
                        ], )
            )
        else :
            return TransactionResponseDestination(
        )
        """

    def testTransactionResponseDestination(self):
        """Test TransactionResponseDestination"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
