# coding: utf-8

"""
Fireblocks API

Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)

The version of the OpenAPI document: 1.6.2
Contact: developers@fireblocks.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from fireblocks.models.order_requirement_details import OrderRequirementDetails


class TestOrderRequirementDetails(unittest.TestCase):
    """OrderRequirementDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderRequirementDetails:
        """Test OrderRequirementDetails
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `OrderRequirementDetails`
        """
        model = OrderRequirementDetails()
        if include_optional:
            return OrderRequirementDetails(
                requirement_id = 'info_7c1f9b2e4a6d',
                due_by = '2024-01-15T10:35Z',
                required_data = '{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["sourceOfFunds", "purposeOfPayment"],
  "properties": {
    "sourceOfFunds": {
      "type": "string",
      "enum": ["SALARY", "SAVINGS", "INVESTMENT_RETURNS", "BUSINESS_INCOME", "OTHER"]
    },
    "purposeOfPayment": {
      "type": "string",
      "enum": ["BUSINESS_EXPENSES", "PERSONAL_EXPENSES", "INVESTMENT", "OTHER"]
    }
  }
}
',
                required_files = [{"fileKey":"identity_document","description":"A clear photo or scan of the account holder's government-issued ID.","allowedFileTypes":["PDF","JPEG","PNG"]}]
            )
        else:
            return OrderRequirementDetails(
                requirement_id = 'info_7c1f9b2e4a6d',
                required_data = '{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["sourceOfFunds", "purposeOfPayment"],
  "properties": {
    "sourceOfFunds": {
      "type": "string",
      "enum": ["SALARY", "SAVINGS", "INVESTMENT_RETURNS", "BUSINESS_INCOME", "OTHER"]
    },
    "purposeOfPayment": {
      "type": "string",
      "enum": ["BUSINESS_EXPENSES", "PERSONAL_EXPENSES", "INVESTMENT", "OTHER"]
    }
  }
}
',
                required_files = [{"fileKey":"identity_document","description":"A clear photo or scan of the account holder's government-issued ID.","allowedFileTypes":["PDF","JPEG","PNG"]}],
        )
        """

    def testOrderRequirementDetails(self):
        """Test OrderRequirementDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
