# coding: utf-8

"""
Fireblocks API

Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)

The version of the OpenAPI document: 1.6.2
Contact: developers@fireblocks.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from fireblocks.models.canton_settlement_details import CantonSettlementDetails


class TestCantonSettlementDetails(unittest.TestCase):
    """CantonSettlementDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CantonSettlementDetails:
        """Test CantonSettlementDetails
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CantonSettlementDetails`
        """
        model = CantonSettlementDetails()
        if include_optional:
            return CantonSettlementDetails(
                version = 1,
                domain = 'ALLOCATION',
                type = 'ALLOCATION_SETTLEMENT',
                original_transaction_id = '9f2b7c14-8d55-4a02-b6e1-5c3f90a7d488'
            )
        else:
            return CantonSettlementDetails(
        )
        """

    def testCantonSettlementDetails(self):
        """Test CantonSettlementDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
