# coding: utf-8

"""
Fireblocks API

Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)

The version of the OpenAPI document: 1.6.2
Contact: developers@fireblocks.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from fireblocks.models.evm_token_create_params_dto import EVMTokenCreateParamsDto


class TestEVMTokenCreateParamsDto(unittest.TestCase):
    """EVMTokenCreateParamsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EVMTokenCreateParamsDto:
        """Test EVMTokenCreateParamsDto
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `EVMTokenCreateParamsDto`
        """
        model = EVMTokenCreateParamsDto()
        if include_optional:
            return EVMTokenCreateParamsDto(
                contract_id = 'b70701f4-d7b1-4795-a8ee-b09cdb5b850d',
                deploy_function_params = [{"internalType":"string","name":"name","type":"string","value":"name"},{"internalType":"string","name":"symbol","type":"string","value":"symbol"},{"components":[{"internalType":"bool","name":"_isMintable","type":"bool"}],"internalType":"struct MyStruct","name":"customConfigProps","type":"tuple","value":[{"internalType":"bool","name":"_isMintable","type":"bool","value":false}]}]
            )
        else:
            return EVMTokenCreateParamsDto(
                contract_id = 'b70701f4-d7b1-4795-a8ee-b09cdb5b850d',
        )
        """

    def testEVMTokenCreateParamsDto(self):
        """Test EVMTokenCreateParamsDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
