# coding: utf-8

"""
    Fireblocks API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.6.2
    Contact: support@fireblocks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import fireblocks_client
from fireblocks_client.models.get_ownership_tokens200_response import GetOwnershipTokens200Response  # noqa: E501
from fireblocks_client.rest import ApiException

class TestGetOwnershipTokens200Response(unittest.TestCase):
    """GetOwnershipTokens200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GetOwnershipTokens200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetOwnershipTokens200Response`
        """
        model = fireblocks_client.models.get_ownership_tokens200_response.GetOwnershipTokens200Response()  # noqa: E501
        if include_optional :
            return GetOwnershipTokens200Response(
                paging = fireblocks_client.models.paging.Paging(
                    next = '', ), 
                data = [
                    fireblocks_client.models.token_ownership_response.TokenOwnershipResponse(
                        id = '', 
                        token_id = '', 
                        standard = '', 
                        metadata_uri = '', 
                        cached_metadata_uri = '', 
                        media = [
                            fireblocks_client.models.media_entity_response.MediaEntityResponse(
                                url = '', 
                                content_type = 'IMAGE', )
                            ], 
                        collection = null, 
                        balance = '', 
                        vault_account_id = '', 
                        ownership_start_time = 1.337, 
                        ownership_last_update_time = 1.337, 
                        blockchain_descriptor = 'ETH', 
                        description = '', 
                        name = '', )
                    ]
            )
        else :
            return GetOwnershipTokens200Response(
        )
        """

    def testGetOwnershipTokens200Response(self):
        """Test GetOwnershipTokens200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
