# coding: utf-8

"""
Fireblocks API

Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)

The version of the OpenAPI document: 1.6.2
Contact: developers@fireblocks.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from fireblocks.models.momo_payment_info import MomoPaymentInfo


class TestMomoPaymentInfo(unittest.TestCase):
    """MomoPaymentInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MomoPaymentInfo:
        """Test MomoPaymentInfo
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `MomoPaymentInfo`
        """
        model = MomoPaymentInfo()
        if include_optional:
            return MomoPaymentInfo(
                rail = 'MOMO',
                addressing_system = 'MOMO',
                account_holder_given_name = 'Kwame',
                account_holder_surname = 'Asante',
                country = 'GH',
                mobile_phone_number = '+233241234567',
                provider = 'MTN',
                beneficiary_document_id = 'GHA-123456789-0',
                beneficiary_relationship = 'Family'
            )
        else:
            return MomoPaymentInfo(
                rail = 'MOMO',
                addressing_system = 'MOMO',
                account_holder_given_name = 'Kwame',
                account_holder_surname = 'Asante',
                country = 'GH',
                mobile_phone_number = '+233241234567',
                provider = 'MTN',
        )
        """

    def testMomoPaymentInfo(self):
        """Test MomoPaymentInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
