# coding: utf-8

"""
Fireblocks API

Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)

The version of the OpenAPI document: 1.6.2
Contact: developers@fireblocks.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from fireblocks.api.compliance_api import ComplianceApi


class TestComplianceApi(unittest.TestCase):
    """ComplianceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ComplianceApi()

    def tearDown(self) -> None:
        pass

    def test_add_address_registry_vault_opt_outs(self) -> None:
        """Test case for add_address_registry_vault_opt_outs

        Add vault accounts to the address registry opt-out list
        """
        pass

    def test_assign_vaults_to_legal_entity(self) -> None:
        """Test case for assign_vaults_to_legal_entity

        Assign vault accounts to a legal entity
        """
        pass

    def test_get_address_registry_tenant_participation_status(self) -> None:
        """Test case for get_address_registry_tenant_participation_status

        Get address registry participation status for the authenticated workspace
        """
        pass

    def test_get_address_registry_vault_opt_out(self) -> None:
        """Test case for get_address_registry_vault_opt_out

        Get whether a vault account is opted out of the address registry
        """
        pass

    def test_get_aml_post_screening_policy(self) -> None:
        """Test case for get_aml_post_screening_policy

        AML - View Post-Screening Policy
        """
        pass

    def test_get_aml_screening_policy(self) -> None:
        """Test case for get_aml_screening_policy

        AML - View Screening Policy
        """
        pass

    def test_get_legal_entity(self) -> None:
        """Test case for get_legal_entity

        Get a legal entity
        """
        pass

    def test_get_legal_entity_by_address(self) -> None:
        """Test case for get_legal_entity_by_address

        [Deprecated] Look up legal entity by address (query parameter)
        """
        pass

    def test_get_legal_entity_for_address(self) -> None:
        """Test case for get_legal_entity_for_address

        Look up legal entity by blockchain address
        """
        pass

    def test_get_post_screening_policy(self) -> None:
        """Test case for get_post_screening_policy

        Travel Rule - View Post-Screening Policy
        """
        pass

    def test_get_screening_full_details(self) -> None:
        """Test case for get_screening_full_details

        Provides all the compliance details for the given screened transaction.
        """
        pass

    def test_get_screening_policy(self) -> None:
        """Test case for get_screening_policy

        Travel Rule - View Screening Policy
        """
        pass

    def test_list_address_registry_vault_opt_outs(self) -> None:
        """Test case for list_address_registry_vault_opt_outs

        List vault-level address registry opt-outs (paginated)
        """
        pass

    def test_list_legal_entities(self) -> None:
        """Test case for list_legal_entities

        List legal entities (Paginated)
        """
        pass

    def test_list_vaults_for_legal_entity(self) -> None:
        """Test case for list_vaults_for_legal_entity

        List vault accounts for a legal entity (Paginated)
        """
        pass

    def test_opt_in_address_registry_tenant(self) -> None:
        """Test case for opt_in_address_registry_tenant

        Opt the workspace in to the address registry
        """
        pass

    def test_opt_out_address_registry_tenant(self) -> None:
        """Test case for opt_out_address_registry_tenant

        Opt the workspace out of the address registry
        """
        pass

    def test_register_legal_entity(self) -> None:
        """Test case for register_legal_entity

        Register a new legal entity
        """
        pass

    def test_remove_address_registry_vault_opt_out(self) -> None:
        """Test case for remove_address_registry_vault_opt_out

        Remove a single vault account from the address registry opt-out list
        """
        pass

    def test_remove_all_address_registry_vault_opt_outs(self) -> None:
        """Test case for remove_all_address_registry_vault_opt_outs

        Remove all vault-level address registry opt-outs for the workspace
        """
        pass

    def test_retry_rejected_transaction_bypass_screening_checks(self) -> None:
        """Test case for retry_rejected_transaction_bypass_screening_checks

        Calling the \"Bypass Screening Policy\" API endpoint triggers a new transaction, with the API user as the initiator, bypassing the screening policy check
        """
        pass

    def test_set_aml_verdict(self) -> None:
        """Test case for set_aml_verdict

        Set AML Verdict for Manual Screening Verdict.
        """
        pass

    def test_update_aml_screening_configuration(self) -> None:
        """Test case for update_aml_screening_configuration

        Update AML Configuration
        """
        pass

    def test_update_legal_entity(self) -> None:
        """Test case for update_legal_entity

        Update legal entity
        """
        pass

    def test_update_screening_configuration(self) -> None:
        """Test case for update_screening_configuration

        Tenant - Screening Configuration
        """
        pass

    def test_update_travel_rule_config(self) -> None:
        """Test case for update_travel_rule_config

        Update Travel Rule Configuration
        """
        pass


if __name__ == "__main__":
    unittest.main()
