# coding: utf-8

"""
    Fireblocks API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.6.2
    Contact: support@fireblocks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fireblocks.models.travel_rule_national_identification import (
    TravelRuleNationalIdentification,
)


class TestTravelRuleNationalIdentification(unittest.TestCase):
    """TravelRuleNationalIdentification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TravelRuleNationalIdentification:
        """Test TravelRuleNationalIdentification
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TravelRuleNationalIdentification`
        """
        model = TravelRuleNationalIdentification()
        if include_optional:
            return TravelRuleNationalIdentification(
                country_of_issue = '',
                national_identifier = '',
                national_identifier_type = '',
                registration_authority = ''
            )
        else:
            return TravelRuleNationalIdentification(
        )
        """

    def testTravelRuleNationalIdentification(self):
        """Test TravelRuleNationalIdentification"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
