# coding: utf-8

"""
Fireblocks API

Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)

The version of the OpenAPI document: 1.6.2
Contact: developers@fireblocks.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from fireblocks.models.disbursement_operation_type import DisbursementOperationType


class TestDisbursementOperationType(unittest.TestCase):
    """DisbursementOperationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDisbursementOperationType(self):
        """Test DisbursementOperationType"""
        # inst = DisbursementOperationType()


if __name__ == "__main__":
    unittest.main()
