# coding: utf-8

"""
Fireblocks API

Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)

The version of the OpenAPI document: 1.6.2
Contact: developers@fireblocks.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from fireblocks.api.onchain_data_api import OnchainDataApi


class TestOnchainDataApi(unittest.TestCase):
    """OnchainDataApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OnchainDataApi()

    def tearDown(self) -> None:
        pass

    def test_get_access_registry_current_state(self) -> None:
        """Test case for get_access_registry_current_state

        Get the current state of addresses in an access registry
        """
        pass

    def test_get_access_registry_summary(self) -> None:
        """Test case for get_access_registry_summary

        Summary of access registry state
        """
        pass

    def test_get_active_roles_for_contract(self) -> None:
        """Test case for get_active_roles_for_contract

        List of active roles for a given contract address and base asset ID
        """
        pass

    def test_get_contract_balance_history(self) -> None:
        """Test case for get_contract_balance_history

        Get historical balance data for a specific account in a contract
        """
        pass

    def test_get_contract_balances_summary(self) -> None:
        """Test case for get_contract_balances_summary

        Get summary for the token contract
        """
        pass

    def test_get_contract_total_supply(self) -> None:
        """Test case for get_contract_total_supply

        Get historical total supply data for a contract
        """
        pass

    def test_get_latest_balances_for_contract(self) -> None:
        """Test case for get_latest_balances_for_contract

        Get latest balances for all addresses holding tokens from a contract
        """
        pass

    def test_get_onchain_transactions(self) -> None:
        """Test case for get_onchain_transactions

        Fetch onchain transactions for a contract
        """
        pass


if __name__ == "__main__":
    unittest.main()
