# coding: utf-8

"""
Fireblocks API

Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)

The version of the OpenAPI document: 1.6.2
Contact: developers@fireblocks.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from fireblocks.models.notification_attempts_paginated_response import (
    NotificationAttemptsPaginatedResponse,
)


class TestNotificationAttemptsPaginatedResponse(unittest.TestCase):
    """NotificationAttemptsPaginatedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NotificationAttemptsPaginatedResponse:
        """Test NotificationAttemptsPaginatedResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `NotificationAttemptsPaginatedResponse`
        """
        model = NotificationAttemptsPaginatedResponse()
        if include_optional:
            return NotificationAttemptsPaginatedResponse(
                data = [
                    fireblocks.models.notification_attempt.NotificationAttempt(
                        sent_time = 1625126400000, 
                        duration = 130, 
                        response_code = 200, 
                        failure_reason = 'TIMED_OUT', )
                    ],
                next = 'eJ0eXAiOiJKV1QiLCJhbGcOiJIUzI1NiJ9'
            )
        else:
            return NotificationAttemptsPaginatedResponse(
                data = [
                    fireblocks.models.notification_attempt.NotificationAttempt(
                        sent_time = 1625126400000, 
                        duration = 130, 
                        response_code = 200, 
                        failure_reason = 'TIMED_OUT', )
                    ],
        )
        """

    def testNotificationAttemptsPaginatedResponse(self):
        """Test NotificationAttemptsPaginatedResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
