# coding: utf-8

"""
Fireblocks API

Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)

The version of the OpenAPI document: 1.6.2
Contact: developers@fireblocks.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from fireblocks.models.tr_link_resolve_action_request import TRLinkResolveActionRequest


class TestTRLinkResolveActionRequest(unittest.TestCase):
    """TRLinkResolveActionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TRLinkResolveActionRequest:
        """Test TRLinkResolveActionRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TRLinkResolveActionRequest`
        """
        model = TRLinkResolveActionRequest()
        if include_optional:
            return TRLinkResolveActionRequest(
                type = 'UPLOAD_BENEFICIARY_PII',
                data = fireblocks.models.tr_link_resolve_action_data.TRLinkResolveActionData(
                    beneficiary_pii = fireblocks.models.tr_link_beneficiary_pii.TRLinkBeneficiaryPii(
                        ivms101 = fireblocks.models.tr_link_ivms.TRLinkIvms(
                            version = 'IVMS101.2023', 
                            data = 'aGVsbG8gd29ybGQgdGhpcyBpcyBlbmNyeXB0ZWQgZGF0YQ==', 
                            filled_fields = ["Beneficiary.beneficiaryPersons[].legalPerson.name.nameIdentifier","Beneficiary.beneficiaryPersons[].naturalPerson.name.nameIdentifier"], ), ), )
            )
        else:
            return TRLinkResolveActionRequest(
                type = 'UPLOAD_BENEFICIARY_PII',
        )
        """

    def testTRLinkResolveActionRequest(self):
        """Test TRLinkResolveActionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
