# coding: utf-8

"""
Fireblocks API

Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)

The version of the OpenAPI document: 1.6.2
Contact: developers@fireblocks.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from fireblocks.models.address_registry_get_vault_opt_out_response import (
    AddressRegistryGetVaultOptOutResponse,
)


class TestAddressRegistryGetVaultOptOutResponse(unittest.TestCase):
    """AddressRegistryGetVaultOptOutResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddressRegistryGetVaultOptOutResponse:
        """Test AddressRegistryGetVaultOptOutResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `AddressRegistryGetVaultOptOutResponse`
        """
        model = AddressRegistryGetVaultOptOutResponse()
        if include_optional:
            return AddressRegistryGetVaultOptOutResponse(
                opted_out = False
            )
        else:
            return AddressRegistryGetVaultOptOutResponse(
                opted_out = False,
        )
        """

    def testAddressRegistryGetVaultOptOutResponse(self):
        """Test AddressRegistryGetVaultOptOutResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
