# coding: utf-8

"""
Fireblocks API

Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)

The version of the OpenAPI document: 1.6.2
Contact: developers@fireblocks.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from fireblocks.models.create_webhook_o_auth_request import CreateWebhookOAuthRequest


class TestCreateWebhookOAuthRequest(unittest.TestCase):
    """CreateWebhookOAuthRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateWebhookOAuthRequest:
        """Test CreateWebhookOAuthRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CreateWebhookOAuthRequest`
        """
        model = CreateWebhookOAuthRequest()
        if include_optional:
            return CreateWebhookOAuthRequest(
                name = 'Production treasury gateway',
                client_id = 'my-client-id',
                client_secret = 'my-client-secret',
                url = 'https://auth.example.com/oauth/token',
                auth_method = 'client_secret_basic',
                custom_jwt_claims = {"aud":"https://auth.example.com","email_verified":true},
                custom_body_params = {"scope":"payments.read payments.write"},
                custom_headers = {"x-api-key":"gateway-key"},
                mtls_client_signed_cert = '-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----'
            )
        else:
            return CreateWebhookOAuthRequest(
                name = 'Production treasury gateway',
                client_id = 'my-client-id',
                client_secret = 'my-client-secret',
                url = 'https://auth.example.com/oauth/token',
        )
        """

    def testCreateWebhookOAuthRequest(self):
        """Test CreateWebhookOAuthRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
