# coding: utf-8

"""
    Fireblocks API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.6.2
    Contact: support@fireblocks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist
from fireblocks_client.models.config_change_request_status import ConfigChangeRequestStatus
from fireblocks_client.models.wallet_asset_additional_info import WalletAssetAdditionalInfo

class ExternalWalletAsset(BaseModel):
    """
    ExternalWalletAsset
    """
    id: Optional[StrictStr] = None
    status: Optional[ConfigChangeRequestStatus] = None
    address: Optional[StrictStr] = None
    tag: Optional[StrictStr] = None
    activation_time: Optional[StrictStr] = Field(None, alias="activationTime")
    additional_info: Optional[conlist(WalletAssetAdditionalInfo)] = Field(None, alias="additionalInfo")
    __properties = ["id", "status", "address", "tag", "activationTime", "additionalInfo"]

    class Config:
        populate_by_name = True
        validate_assignment = True
        arbitrary_types_allowed = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ExternalWalletAsset:
        """Create an instance of ExternalWalletAsset from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in additional_info (list)
        _items = []
        if self.additional_info:
            for _item in self.additional_info:
                if _item:
                    _items.append(_item.to_dict())
            _dict['additionalInfo'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ExternalWalletAsset:
        """Create an instance of ExternalWalletAsset from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return ExternalWalletAsset.parse_obj(obj)

        _obj = ExternalWalletAsset.parse_obj({
            "id": obj.get("id"),
            "status": obj.get("status"),
            "address": obj.get("address"),
            "tag": obj.get("tag"),
            "activation_time": obj.get("activationTime"),
            "additional_info": [WalletAssetAdditionalInfo.from_dict(_item) for _item in obj.get("additionalInfo")] if obj.get("additionalInfo") is not None else None
        })
        return _obj

