# coding: utf-8

"""
    Fireblocks API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.6.2
    Contact: support@fireblocks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, conlist
from fireblocks_client.models.xb_settlement_config_model import XBSettlementConfigModel

class XBSettlementGetAllConfigsResponse(BaseModel):
    """
    XBSettlementGetAllConfigsResponse
    """
    configurations: conlist(XBSettlementConfigModel) = ...
    __properties = ["configurations"]

    class Config:
        populate_by_name = True
        validate_assignment = True
        arbitrary_types_allowed = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> XBSettlementGetAllConfigsResponse:
        """Create an instance of XBSettlementGetAllConfigsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in configurations (list)
        _items = []
        if self.configurations:
            for _item in self.configurations:
                if _item:
                    _items.append(_item.to_dict())
            _dict['configurations'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> XBSettlementGetAllConfigsResponse:
        """Create an instance of XBSettlementGetAllConfigsResponse from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return XBSettlementGetAllConfigsResponse.parse_obj(obj)

        _obj = XBSettlementGetAllConfigsResponse.parse_obj({
            "configurations": [XBSettlementConfigModel.from_dict(_item) for _item in obj.get("configurations")] if obj.get("configurations") is not None else None
        })
        return _obj

