# coding: utf-8

"""
    Fireblocks API

    Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 

    The version of the OpenAPI document: 1.6.2
    Contact: developers@fireblocks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBytes, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class AddConnectedAccountRequest(BaseModel):
    """
    AddConnectedAccountRequest
    """ # noqa: E501
    provider_id: StrictStr = Field(description="Integration key identifying the provider (e.g. BINANCE, KINGDOM_BANK, GEMINI_NLV2).", alias="providerId")
    display_name: Optional[StrictStr] = Field(default=None, description="Human-readable account name. Required for non-NLV2 providers.", alias="displayName")
    creds: Union[StrictBytes, StrictStr] = Field(description="Base64-encoded RSA-encrypted credential blob. Encrypt using the public key from GET /exchange_accounts/credentials_public_key.")
    api_key: StrictStr = Field(description="Account-level API key.", alias="apiKey")
    main_account_id: Optional[StrictStr] = Field(default=None, description="Parent main account ID for sub-account creation. Not allowed for NLV2 providers.", alias="mainAccountId")
    account_id: Optional[StrictStr] = Field(default=None, description="Optional provider-side account ID to associate with the created account.", alias="accountId")
    on_premise_server_id: Optional[StrictStr] = Field(default=None, description="On-premise server ID for self-hosted integrations.", alias="onPremiseServerId")
    __properties: ClassVar[List[str]] = ["providerId", "displayName", "creds", "apiKey", "mainAccountId", "accountId", "onPremiseServerId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AddConnectedAccountRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AddConnectedAccountRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "providerId": obj.get("providerId"),
            "displayName": obj.get("displayName"),
            "creds": obj.get("creds"),
            "apiKey": obj.get("apiKey"),
            "mainAccountId": obj.get("mainAccountId"),
            "accountId": obj.get("accountId"),
            "onPremiseServerId": obj.get("onPremiseServerId")
        })
        return _obj


