# coding: utf-8

"""
    Fireblocks API

    Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 

    The version of the OpenAPI document: 1.6.2
    Contact: developers@fireblocks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AllowlistEntryStatus(str, Enum):
    """
    Current status of the allowlist entry.   - `ACTIVE` — Entry is approved and usable.   - `PENDING_PROVIDER_COOLDOWN` — Entry was recently added or modified and is in the provider-enforced cooldown window before becoming active.   - `PENDING_PROVIDER_REVIEW` — Entry is awaiting provider-side review.   - `PENDING_APPROVAL` — Entry is awaiting customer/admin approval on the Fireblocks side.   - `REJECTED` — Entry was rejected at submission time and will not become active.   - `REMOVED` — Entry was deactivated after previously being active. May still appear in results for audit purposes. 
    """

    """
    allowed enum values
    """
    ACTIVE = 'ACTIVE'
    PENDING_PROVIDER_COOLDOWN = 'PENDING_PROVIDER_COOLDOWN'
    PENDING_PROVIDER_REVIEW = 'PENDING_PROVIDER_REVIEW'
    PENDING_APPROVAL = 'PENDING_APPROVAL'
    REJECTED = 'REJECTED'
    REMOVED = 'REMOVED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AllowlistEntryStatus from a JSON string"""
        return cls(json.loads(json_str))


