# coding: utf-8

"""
    Fireblocks API

    Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 

    The version of the OpenAPI document: 1.6.2
    Contact: developers@fireblocks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class FpsHkPaymentInfo(BaseModel):
    """
    FPS HK payment information for Hong Kong Faster Payment System transfers (HKD)
    """ # noqa: E501
    rail: StrictStr = Field(description="The payment rail type for Hong Kong FPS transfers")
    addressing_system: StrictStr = Field(description="The addressing system used for Hong Kong FPS transfers", alias="addressingSystem")
    recipient_legal_name: Optional[StrictStr] = Field(default=None, description="Full legal name of the recipient", alias="recipientLegalName")
    account_number: Optional[StrictStr] = Field(default=None, description="Recipient bank account number", alias="accountNumber")
    bank_code: Optional[StrictStr] = Field(default=None, description="Hong Kong bank code", alias="bankCode")
    phone: Optional[StrictStr] = Field(default=None, description="Recipient phone number in E.164 format")
    email: Optional[StrictStr] = Field(default=None, description="Recipient email address")
    fps_id: Optional[StrictStr] = Field(default=None, description="Hong Kong FPS identifier", alias="fpsId")
    __properties: ClassVar[List[str]] = ["rail", "addressingSystem", "recipientLegalName", "accountNumber", "bankCode", "phone", "email", "fpsId"]

    @field_validator('rail')
    def rail_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['FPS_HK']):
            raise ValueError("must be one of enum values ('FPS_HK')")
        return value

    @field_validator('addressing_system')
    def addressing_system_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['FPS_HK']):
            raise ValueError("must be one of enum values ('FPS_HK')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FpsHkPaymentInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FpsHkPaymentInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "rail": obj.get("rail"),
            "addressingSystem": obj.get("addressingSystem"),
            "recipientLegalName": obj.get("recipientLegalName"),
            "accountNumber": obj.get("accountNumber"),
            "bankCode": obj.get("bankCode"),
            "phone": obj.get("phone"),
            "email": obj.get("email"),
            "fpsId": obj.get("fpsId")
        })
        return _obj


