# coding: utf-8

"""
    Fireblocks API

    Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 

    The version of the OpenAPI document: 1.6.2
    Contact: developers@fireblocks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class PayidPaymentInfo(BaseModel):
    """
    PayID payment information for Australian dollar transfers
    """ # noqa: E501
    rail: StrictStr = Field(description="The payment rail type for PayID transfers")
    addressing_system: StrictStr = Field(description="The addressing system used for PayID transfers", alias="addressingSystem")
    account_holder_given_name: StrictStr = Field(description="The given name (first name) of the account holder", alias="accountHolderGivenName")
    account_holder_surname: StrictStr = Field(description="The surname (last name) of the account holder", alias="accountHolderSurname")
    country: StrictStr = Field(description="The country for the transfer (ISO 3166-1 alpha-2 code)")
    value: StrictStr = Field(description="The PayID identifier (email, phone, ABN, or organization ID)")
    type: StrictStr = Field(description="The type of PayID being used")
    bsb: Optional[StrictStr] = Field(default=None, description="Bank State Branch (BSB) number (6 digits, format XXX-XXX)")
    account_number: StrictStr = Field(description="Australian bank account number", alias="accountNumber")
    __properties: ClassVar[List[str]] = ["rail", "addressingSystem", "accountHolderGivenName", "accountHolderSurname", "country", "value", "type", "bsb", "accountNumber"]

    @field_validator('rail')
    def rail_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['PAYID']):
            raise ValueError("must be one of enum values ('PAYID')")
        return value

    @field_validator('addressing_system')
    def addressing_system_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['PAYID']):
            raise ValueError("must be one of enum values ('PAYID')")
        return value

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['EMAIL']):
            raise ValueError("must be one of enum values ('EMAIL')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PayidPaymentInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PayidPaymentInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "rail": obj.get("rail"),
            "addressingSystem": obj.get("addressingSystem"),
            "accountHolderGivenName": obj.get("accountHolderGivenName"),
            "accountHolderSurname": obj.get("accountHolderSurname"),
            "country": obj.get("country"),
            "value": obj.get("value"),
            "type": obj.get("type"),
            "bsb": obj.get("bsb"),
            "accountNumber": obj.get("accountNumber")
        })
        return _obj


