# coding: utf-8

"""
    Fireblocks API

    Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 

    The version of the OpenAPI document: 1.6.2
    Contact: developers@fireblocks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Position2(BaseModel):
    """
    Position2
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Position UUID.")
    status: Optional[StrictStr] = Field(default=None, description="Lifecycle status of the position.")
    in_flight: Optional[StrictBool] = Field(default=None, description="True while an action is in progress for this position.", alias="inFlight")
    position_type: Optional[StrictStr] = Field(default=None, description="Whether the position is lend- or borrow-side.", alias="positionType")
    vault_account_id: Optional[StrictStr] = Field(default=None, description="Fireblocks vault account holding the position.", alias="vaultAccountId")
    opportunity_id: Optional[StrictStr] = Field(default=None, description="Opportunity / vault or market identifier.", alias="opportunityId")
    chain_id: Optional[StrictStr] = Field(default=None, description="Chain identifier as a string (e.g. \"1\").", alias="chainId")
    provider_id: Optional[StrictStr] = Field(default=None, description="Lending protocol.", alias="providerId")
    origin: Optional[StrictStr] = Field(default=None, description="Whether the position was opened natively in Fireblocks or imported externally.")
    principal_asset_id: Optional[StrictStr] = Field(default=None, description="Fireblocks asset id for the principal (underlying) asset.", alias="principalAssetId")
    position_asset_id: Optional[StrictStr] = Field(default=None, description="Fireblocks asset id for the position / share token.", alias="positionAssetId")
    principal_balance: Optional[StrictStr] = Field(default=None, description="Human-readable principal balance.", alias="principalBalance")
    position_balance: Optional[StrictStr] = Field(default=None, description="Human-readable position token balance.", alias="positionBalance")
    created_at: Optional[StrictStr] = Field(default=None, description="Creation time (ISO-8601).", alias="createdAt")
    updated_at: Optional[StrictStr] = Field(default=None, description="Last update time (ISO-8601).", alias="updatedAt")
    last_synced_at: Optional[StrictStr] = Field(default=None, description="Last successful on-chain sync time (ISO-8601).", alias="lastSyncedAt")
    available_actions: Optional[List[StrictStr]] = Field(default=None, description="Actions the API allows next for this position.", alias="availableActions")
    __properties: ClassVar[List[str]] = ["id", "status", "inFlight", "positionType", "vaultAccountId", "opportunityId", "chainId", "providerId", "origin", "principalAssetId", "positionAssetId", "principalBalance", "positionBalance", "createdAt", "updatedAt", "lastSyncedAt", "availableActions"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ACTIVE', 'INACTIVE']):
            raise ValueError("must be one of enum values ('ACTIVE', 'INACTIVE')")
        return value

    @field_validator('position_type')
    def position_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['LEND', 'BORROW']):
            raise ValueError("must be one of enum values ('LEND', 'BORROW')")
        return value

    @field_validator('provider_id')
    def provider_id_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['MORPHO', 'AAVE']):
            raise ValueError("must be one of enum values ('MORPHO', 'AAVE')")
        return value

    @field_validator('origin')
    def origin_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NATIVE', 'EXTERNAL']):
            raise ValueError("must be one of enum values ('NATIVE', 'EXTERNAL')")
        return value

    @field_validator('available_actions')
    def available_actions_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['DEPOSIT', 'WITHDRAW']):
                raise ValueError("each list item must be one of ('DEPOSIT', 'WITHDRAW')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Position2 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Position2 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "status": obj.get("status"),
            "inFlight": obj.get("inFlight"),
            "positionType": obj.get("positionType"),
            "vaultAccountId": obj.get("vaultAccountId"),
            "opportunityId": obj.get("opportunityId"),
            "chainId": obj.get("chainId"),
            "providerId": obj.get("providerId"),
            "origin": obj.get("origin"),
            "principalAssetId": obj.get("principalAssetId"),
            "positionAssetId": obj.get("positionAssetId"),
            "principalBalance": obj.get("principalBalance"),
            "positionBalance": obj.get("positionBalance"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "lastSyncedAt": obj.get("lastSyncedAt"),
            "availableActions": obj.get("availableActions")
        })
        return _obj


