# coding: utf-8

"""
    Fireblocks API

    Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 

    The version of the OpenAPI document: 1.6.2
    Contact: developers@fireblocks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from fireblocks.models.access_type import AccessType
from fireblocks.models.transfer_rail import TransferRail
from typing import Optional, Set
from typing_extensions import Self

class Rate(BaseModel):
    """
    Rate
    """ # noqa: E501
    via: AccessType
    base_asset_id: StrictStr = Field(description="The source asset identifier", alias="baseAssetId")
    base_asset_rail: Optional[TransferRail] = Field(default=None, alias="baseAssetRail")
    quote_asset_id: StrictStr = Field(description="The target asset identifier", alias="quoteAssetId")
    quote_asset_rail: Optional[TransferRail] = Field(default=None, alias="quoteAssetRail")
    rate: Annotated[str, Field(strict=True)] = Field(description="The indicative exchange rate — the number of units of the quote asset that equal 1 unit of the base asset. For example, if base is BTC and quote is USD, a rate of 75000 means 1 BTC = 75,000 USD.")
    __properties: ClassVar[List[str]] = ["via", "baseAssetId", "baseAssetRail", "quoteAssetId", "quoteAssetRail", "rate"]

    @field_validator('rate')
    def rate_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^\d+(\.\d+)?$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Rate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of via
        if self.via:
            _dict['via'] = self.via.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Rate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "via": AccessType.from_dict(obj["via"]) if obj.get("via") is not None else None,
            "baseAssetId": obj.get("baseAssetId"),
            "baseAssetRail": obj.get("baseAssetRail"),
            "quoteAssetId": obj.get("quoteAssetId"),
            "quoteAssetRail": obj.get("quoteAssetRail"),
            "rate": obj.get("rate")
        })
        return _obj


