# coding: utf-8

"""
    Fireblocks API

    Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 

    The version of the OpenAPI document: 1.6.2
    Contact: developers@fireblocks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from fireblocks.models.transfer_direction_enum import TransferDirectionEnum
from typing import Optional, Set
from typing_extensions import Self

class ScreeningPayload(BaseModel):
    """
    The subject of the screening. Which fields are required depends on the operation and on the connectors configured on the workflow's step.
    """ # noqa: E501
    blockchain: Optional[StrictStr] = Field(default=None, description="The blockchain network of the asset being screened.")
    asset: Optional[StrictStr] = Field(default=None, description="The asset identifier being screened.")
    asset_amount: Optional[StrictStr] = Field(default=None, description="The amount of the asset involved in the transaction, as a string.", alias="assetAmount")
    usd_value: Optional[StrictStr] = Field(default=None, description="The USD value of the transaction amount, as a string.", alias="usdValue")
    customer_ref_id: Optional[StrictStr] = Field(default=None, description="Customer-provided reference identifier for tracking.", alias="customerRefId")
    external_id: Optional[StrictStr] = Field(default=None, description="External identifier for the screening (provider-specific).", alias="externalId")
    address: Optional[StrictStr] = Field(default=None, description="The blockchain address to screen. Used for the `ADDRESS_SCREENING` operation.")
    direction: Optional[TransferDirectionEnum] = None
    source_address: Optional[List[StrictStr]] = Field(default=None, description="The source blockchain address(es) of the transaction.", alias="sourceAddress")
    destination_address: Optional[List[StrictStr]] = Field(default=None, description="The destination blockchain address(es) of the transaction.", alias="destinationAddress")
    tx_hash: Optional[StrictStr] = Field(default=None, description="The transaction hash on the blockchain.", alias="txHash")
    __properties: ClassVar[List[str]] = ["blockchain", "asset", "assetAmount", "usdValue", "customerRefId", "externalId", "address", "direction", "sourceAddress", "destinationAddress", "txHash"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ScreeningPayload from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ScreeningPayload from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "blockchain": obj.get("blockchain"),
            "asset": obj.get("asset"),
            "assetAmount": obj.get("assetAmount"),
            "usdValue": obj.get("usdValue"),
            "customerRefId": obj.get("customerRefId"),
            "externalId": obj.get("externalId"),
            "address": obj.get("address"),
            "direction": obj.get("direction"),
            "sourceAddress": obj.get("sourceAddress"),
            "destinationAddress": obj.get("destinationAddress"),
            "txHash": obj.get("txHash")
        })
        return _obj


