# coding: utf-8

"""
    Fireblocks API

    Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 

    The version of the OpenAPI document: 1.6.2
    Contact: developers@fireblocks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class TRLinkSetDestinationTravelRuleMessageIdResponse(BaseModel):
    """
    TRLinkSetDestinationTravelRuleMessageIdResponse
    """ # noqa: E501
    success: StrictBool = Field(description="Whether the operation was successful")
    updated_destinations: Union[StrictFloat, StrictInt] = Field(description="Number of destinations updated", alias="updatedDestinations")
    failed_destinations: Union[StrictFloat, StrictInt] = Field(description="Number of destinations that failed to update", alias="failedDestinations")
    errors: Optional[List[StrictStr]] = Field(default=None, description="List of errors (if any)")
    __properties: ClassVar[List[str]] = ["success", "updatedDestinations", "failedDestinations", "errors"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TRLinkSetDestinationTravelRuleMessageIdResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if errors (nullable) is None
        # and model_fields_set contains the field
        if self.errors is None and "errors" in self.model_fields_set:
            _dict['errors'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TRLinkSetDestinationTravelRuleMessageIdResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "success": obj.get("success"),
            "updatedDestinations": obj.get("updatedDestinations"),
            "failedDestinations": obj.get("failedDestinations"),
            "errors": obj.get("errors")
        })
        return _obj


