# coding: utf-8

"""
    Fireblocks API

    Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 

    The version of the OpenAPI document: 1.6.2
    Contact: developers@fireblocks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from fireblocks.models.utxo_identifier import UtxoIdentifier
from typing import Optional, Set
from typing_extensions import Self

class UtxoLabelFailure(BaseModel):
    """
    A requested identifier that blocked the label request, with the reason it could not be labelled.
    """ # noqa: E501
    identifier: UtxoIdentifier = Field(description="The identifier exactly as it was sent in the request.")
    reason: StrictStr = Field(description="Why the identifier could not be labelled: - `NOT_FOUND` — no UTXO for it in this vault and asset. Retrying can work once it is indexed. - `NOT_LABELLABLE` — the UTXO exists but can no longer be labelled (spent, or removed; for a transaction ID, every output). Retrying will not help.")
    utxo_status: Optional[StrictStr] = Field(default=None, description="The UTXO status behind the reason, when one explains it. With `NOT_FOUND`, `REMOVED` means the UTXO was removed within the last hour and may still reappear; if it does not, the same request returns `NOT_LABELLABLE` after about an hour.", alias="utxoStatus")
    __properties: ClassVar[List[str]] = ["identifier", "reason", "utxoStatus"]

    @field_validator('reason')
    def reason_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['NOT_FOUND', 'NOT_LABELLABLE', 'UNUSABLE_IDENTIFIER']):
            raise ValueError("must be one of enum values ('NOT_FOUND', 'NOT_LABELLABLE', 'UNUSABLE_IDENTIFIER')")
        return value

    @field_validator('utxo_status')
    def utxo_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['SPENT', 'REMOVED']):
            raise ValueError("must be one of enum values ('SPENT', 'REMOVED')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UtxoLabelFailure from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of identifier
        if self.identifier:
            _dict['identifier'] = self.identifier.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UtxoLabelFailure from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "identifier": UtxoIdentifier.from_dict(obj["identifier"]) if obj.get("identifier") is not None else None,
            "reason": obj.get("reason"),
            "utxoStatus": obj.get("utxoStatus")
        })
        return _obj


