"""
Fireblocks API

Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)

The version of the OpenAPI document: 1.6.2
Contact: developers@fireblocks.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from typing import Optional

from fireblocks.configuration import Configuration

"""This class is the Configuration handed to ApiClient, extended with the
Fireblocks-specific transport settings that the generated Configuration does not
declare. Mirrors the layering of the public configuration: Fireblocks takes a
ClientConfiguration, ApiClient takes an ApiClientConfiguration.
:param connection_idle_timeout_sec: Seconds a pooled connection may sit idle before it is discarded.
"""


class ApiClientConfiguration(Configuration):

    def __init__(
        self, *args, connection_idle_timeout_sec: Optional[float] = None, **kwargs
    ) -> None:
        super().__init__(*args, **kwargs)
        # Read by rest.py when it builds the connection pool manager. None means
        # "not configured"; connection_pool.py applies the SDK default.
        self.connection_idle_timeout_sec = connection_idle_timeout_sec
